"""Add unique to slug

Revision ID: e8531b38ca33
Revises: c05d2a225196
Create Date: 2023-07-20 12:15:31.840130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8531b38ca33'
down_revision = 'c05d2a225196'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('test', sa.String(), nullable=True))
    op.create_index(op.f('ix_blog_slug'), 'blog', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_slug'), table_name='blog')
    op.drop_column('blog', 'test')
    # ### end Alembic commands ###
